#!/usr/bin/python3
# -*- coding: utf-8 -*-
'''
@date: 2016-10-29
@author: Shell.Xu
@copyright: 2016, Shell.Xu <shell909090@gmail.com>
@license: BSD-3-clause
'''


if __name__ == '__main__':
    import uft
    import uft_dup
    import uft_mount
    uft.main()
