#!/bin/bash

gitclone() {
    local url
    url="$1"

    if [ ${url:${#url}-4} = ".git" ]; then
	url=${url::${#url}-4} # remove .git in tail
    fi

    if [[ "$url" == *"://"* ]]; then 
	# {scheme}://github.com/shell909090/goproxy.git
	url=$(echo "$url" | awk -F:// '{print $2}')
    else
	# git@github.com:shell909090/emacscfg.git
	url=$(echo "$url" | awk -F@ '{gsub(/:/,"/",$2); print $2}') # split @ and replace : to /
    fi

    mkdir -p ~/src/"$url"
    cd $(dirname ~/src/"$url")
    git clone "$1"
    cd ~/src/"$url"
}
