#!/bin/bash

# 导入一个函数，在locate中搜索关键词，得到应当转跳的目录，并提供给用户选择。
cdjump() {
    local prefix=$1
    local result
    local line
    local num
    local k=0

    for line in $(mlocate $prefix)
    do
	if [ -z $(echo "$line" | grep "$prefix.*/") ] && [ -d "$line" ]
	then
	    result[k++]="$line"
	fi
    done

    select num in ${result[*]};
    do
    	cd $num
	break
    done
}
