#!/bin/bash

lang="chi_sim"
pdf="$1"
tmpdir=$(mktemp -d)
trap 'rm -rf -- "$tmpdir"' EXIT

# pdfimages "$pdf" "$tmpdir/img"
convert -density 300 "$pdf" "$tmpdir/img-%03d.png"
find "$tmpdir" -type f | sort | parallel -j1 tesseract -l "$lang" {} {.}
find "$tmpdir" -name "*.txt" | sort | xargs cat > $(basename "$pdf" .pdf)".txt"
